version: '3.8'

# services:
#   loginjwt:
#     image: loginjwt
#     build: .
#     ports:
#       - "8080:8080"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#   sql-server-db:
#     container_name: '${serverName}_DB'
#     image: mcr.microsoft.com/mssql/server:2022-latest
#     ports:
#       - "1433:1433"
#     environment:
#       SA_PASSWORD: "${BD_password}"
#       ACCEPT_EULA: "Y"

services:
  sql-server-db:
    container_name: '${serverName}_DB'
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${BD_password}"
      ACCEPT_EULA: "Y"